# On démarre un conteneur basé sur l'image Windows spécifiée. 
# Si l'image n'existe pas, elle sera téléchargée
FROM mcr.microsoft.com/windows/nanoserver:1803

# On exécute une commande afin d'afficher un message
CMD echo Hello World!